Repository styled-components/styled-components, pull requests merged in 2019-05, with the labels that each got.

#2522 [WIP] Implement new sheet logic
  .eslintrc.json
  package.json
  packages/benchmarks/index.html
  packages/benchmarks/package.json
  packages/benchmarks/run-headless.js
  packages/benchmarks/src/app/App.js
  packages/benchmarks/src/implementations/styled-components-v4/.gitattributes
  packages/benchmarks/src/implementations/styled-components-v4/Box.js
  packages/benchmarks/src/implementations/styled-components-v4/Dot.js
  packages/benchmarks/src/implementations/styled-components-v4/Provider.js
  packages/benchmarks/src/implementations/styled-components-v4/View.js
  packages/benchmarks/src/implementations/styled-components-v4/index.js
  packages/benchmarks/src/implementations/styled-components-v4/styled-components-v4.esm.js
  packages/benchmarks/src/implementations/styled-components/Dot.js
  packages/benchmarks/src/index.js
  packages/benchmarks/webpack.config.js
  packages/styled-components/package.json
  packages/styled-components/rollup.config.js
  packages/styled-components/src/constants.js
  packages/styled-components/src/constructors/createGlobalStyle.js
  packages/styled-components/src/constructors/keyframes.js
  packages/styled-components/src/models/ComponentStyle.js
  packages/styled-components/src/models/GlobalStyle.js
  packages/styled-components/src/models/InlineStyle.js
  packages/styled-components/src/models/Keyframes.js
  packages/styled-components/src/models/ServerStyleSheet.js
  packages/styled-components/src/models/StyleSheet.js
  packages/styled-components/src/models/StyleSheetManager.js
  packages/styled-components/src/models/StyleTags.js
  packages/styled-components/src/models/StyledComponent.js
  packages/styled-components/src/secretInternals.js
  packages/styled-components/src/sheet/GroupIDAllocator.js
  packages/styled-components/src/sheet/GroupedTag.js
  packages/styled-components/src/sheet/Rehydration.js
  packages/styled-components/src/sheet/Sheet.js
  packages/styled-components/src/sheet/Tag.js
  packages/styled-components/src/sheet/dom.js
  packages/styled-components/src/sheet/index.js
  packages/styled-components/src/sheet/types.js
  packages/styled-components/src/test/utils.js
  packages/styled-components/src/utils/extractCompsFromCSS.js
  packages/styled-components/src/utils/flatten.js
  packages/styled-components/src/utils/generateAlphabeticName.js
  packages/styled-components/src/utils/hasher.js
  packages/styled-components/src/utils/insertRuleHelpers.js
  packages/styled-components/src/utils/nonce.js
  packages/styled-components/src/utils/stringifyRules.js
  packages/styled-components/src/utils/styleNames.js
  packages/styled-components/src/utils/test/classNameUsageCheckInjector.test.js
  packages/styled-components/src/utils/test/extractCompsFromCSS.test.js
  packages/styled-components/src/utils/test/styleNames.test.js
  packages/styled-components/src/utils/useCheckClassNameUsage.js
  packages/styled-components/src/vendor/glamor/hash.js
  yarn.lock
Labels: canary v5

#2489 Fix objects with functions - replace (objToCss) with (objToCssArray)
  CHANGELOG.md
  packages/styled-components/src/constructors/test/createGlobalStyle.test.js
  packages/styled-components/src/test/basic.test.js
  packages/styled-components/src/utils/flatten.js
  packages/styled-components/src/utils/test/flatten.test.js
Labels: 4.0

#2427 Fix macro with ts
  CHANGELOG.md
  packages/styled-components/src/macro/index.js
  packages/styled-components/src/macro/test/__snapshots__/macro.test.js.snap
  packages/styled-components/src/macro/test/macro.test.js
Labels: 4.0

#2569 Fix tests for canary changes
  packages/styled-components/src/constructors/test/createGlobalStyle.test.js
  packages/styled-components/src/constructors/test/keyframes.test.js
  packages/styled-components/src/macro/test/__snapshots__/macro.test.js.snap
  packages/styled-components/src/macro/test/macro.test.js
  packages/styled-components/src/models/StyledComponent.js
  packages/styled-components/src/models/test/StyleSheetManager.test.js
  packages/styled-components/src/models/test/__snapshots__/StyleSheetManager.test.js.snap
  packages/styled-components/src/sheet/dom.js
  packages/styled-components/src/test/__snapshots__/expanded-api.test.js.snap
  packages/styled-components/src/test/__snapshots__/ssr.test.js.snap
  packages/styled-components/src/test/attrs.test.js
  packages/styled-components/src/test/basic.test.js
  packages/styled-components/src/test/constants.test.js
  packages/styled-components/src/test/css.test.js
  packages/styled-components/src/test/expanded-api.test.js
  packages/styled-components/src/test/overriding.test.js
  packages/styled-components/src/test/rehydration.test.js
  packages/styled-components/src/test/ssr.test.js
  packages/styled-components/src/test/styles.test.js
Labels: canary v5

#2571 Add tests for canary sheet implementation
  packages/styled-components/src/sheet/Rehydration.js
  packages/styled-components/src/sheet/Tag.js
  packages/styled-components/src/sheet/test/GroupIDAllocator.test.js
  packages/styled-components/src/sheet/test/GroupedTag.test.js
  packages/styled-components/src/sheet/test/Rehydration.test.js
  packages/styled-components/src/sheet/test/Sheet.test.js
  packages/styled-components/src/sheet/test/Tag.test.js
  packages/styled-components/src/sheet/test/dom.test.js
Labels: canary v5

#2572 Fix IE11 quirk in canary when accessing cssText
  packages/styled-components/src/sheet/Rehydration.js
  packages/styled-components/src/sheet/Tag.js
Labels: bug :bug:, canary v5

#2565 allow dynamic creation & configuration of stylis per stylesheet
  .eslintrc.json
  packages/styled-components/package.json
  packages/styled-components/src/constructors/keyframes.js
  packages/styled-components/src/models/ComponentStyle.js
  packages/styled-components/src/models/GlobalStyle.js
  packages/styled-components/src/models/Keyframes.js
  packages/styled-components/src/models/StyleSheetManager.js
  packages/styled-components/src/models/test/StyleSheetManager.test.js
  packages/styled-components/src/sheet/Sheet.js
  packages/styled-components/src/sheet/types.js
  packages/styled-components/src/test/overriding.test.js
  packages/styled-components/src/utils/stringifyRules.js
  packages/styled-components/src/utils/stylis.js
  yarn.lock
Labels: canary v5

#2542 replace objectToCss with objectWithCssArray
  packages/styled-components/src/test/basic.test.js
  packages/styled-components/src/utils/flatten.js
  packages/styled-components/src/utils/test/flatten.test.js
Labels: canary v5

#2574 v4.2.1
  CHANGELOG.md
  packages/styled-components/package.json
Labels: 4.0

#2567 Fix #2367 in a cleaner way, but with more refactoring
  CHANGELOG.md
  packages/styled-components/src/models/StyledComponent.js
  packages/styled-components/src/models/StyledNativeComponent.js
  packages/styled-components/src/native/test/native.test.js
Labels: 4.0
