Repository styled-components/styled-components, pull requests merged in 2019-06, with the labels that each got.

#2580 implement forwardedAs for 4.x
  CHANGELOG.md
  packages/styled-components/src/models/StyledComponent.js
  packages/styled-components/src/models/StyledNativeComponent.js
  packages/styled-components/src/native/test/native.test.js
  packages/styled-components/src/test/props.test.js
Labels: 4.0

#2573 add forwardedAs prop
  packages/styled-components/src/models/StyledComponent.js
  packages/styled-components/src/models/StyledNativeComponent.js
  packages/styled-components/src/native/test/native.test.js
  packages/styled-components/src/test/props.test.js
Labels: canary v5

#2585 use shallowequal for equivalency checking instead
  packages/styled-components/package.json
  packages/styled-components/src/models/StyleSheetManager.js
  yarn.lock
Labels: canary v5

#2586 prevent component folding when interim HOCs are present
  CHANGELOG.md
  packages/styled-components/src/models/StyledComponent.js
  packages/styled-components/src/models/StyledNativeComponent.js
  packages/styled-components/src/test/basic.test.js
  packages/styled-components/src/utils/isStyledComponent.js
  packages/styled-components/src/utils/test/isStyledComponent.test.js
Labels: 4.0

#2587 prevent folding for interim HOCs & fix subtle className composition bug
  packages/styled-components/src/models/StyledComponent.js
  packages/styled-components/src/models/StyledNativeComponent.js
  packages/styled-components/src/test/__snapshots__/attrs.test.js.snap
  packages/styled-components/src/test/attrs.test.js
  packages/styled-components/src/test/basic.test.js
  packages/styled-components/src/utils/isStyledComponent.js
Labels: canary v5

#2501 Make possible to initialize SC_ATTR via REACT_APP_SC_ATTR env variable
  CHANGELOG.md
  packages/styled-components/src/constants.js
  packages/styled-components/src/test/constants.test.js
Labels: 4.0

#2597 implement folding of defaultProps
  CHANGELOG.md
  packages/styled-components/.eslintignore
  packages/styled-components/.flowconfig
  packages/styled-components/flow-typed/npm/@babel/helper-module-imports_vx.x.x.js
  packages/styled-components/flow-typed/npm/babel-plugin-styled-components_vx.x.x.js
  packages/styled-components/flow-typed/npm/merge-anything_vx.x.x.js
  packages/styled-components/flow-typed/npm/prop-types_v15.x.x.js
  packages/styled-components/flow-typed/npm/react-is_vx.x.x.js
  packages/styled-components/flow-typed/npm/react-test-renderer_v16.x.x.js
  packages/styled-components/flow-typed/npm/supports-color_vx.x.x.js
  packages/styled-components/package.json
  packages/styled-components/src/models/StyledComponent.js
  packages/styled-components/src/models/StyledNativeComponent.js
  packages/styled-components/src/native/test/native.test.js
  packages/styled-components/src/test/basic.test.js
  packages/styled-components/src/utils/isFunction.js
  yarn.lock
Labels: 4.0

#2588 peer dependency & globals adjustments for bundle size
  CHANGELOG.md
  package.json
  packages/styled-components/package.json
  packages/styled-components/rollup.config.js
  packages/styled-components/src/models/StyleSheetManager.js
  yarn.lock
Labels: canary v5

#2581 add seal fn back to ServerStyleSheet for backward compat
  packages/styled-components/src/models/ServerStyleSheet.js
  packages/styled-components/src/test/__snapshots__/ssr.test.js.snap
  packages/styled-components/src/test/ssr.test.js
  src/utils/errors.md
Labels: canary v5

#2611 v4 backward-compat fix on ServerStyleSheet.getStyleElement
  packages/styled-components/src/models/ServerStyleSheet.js
  packages/styled-components/src/test/ssr.test.js
Labels: canary v5

#2621 fix inconsistency between client & server that breaks rehydration
  packages/styled-components/src/models/ComponentStyle.js
  packages/styled-components/src/test/__snapshots__/ssr.test.js.snap
Labels: 5.0

#2633 fix css props when using babel macro with babel-plugin-styled-components 1.10.1
  CHANGELOG.md
  packages/styled-components/flow-typed/npm/@babel/traverse_vx.x.x.js
  packages/styled-components/package.json
  packages/styled-components/src/macro/index.js
  packages/styled-components/src/macro/test/__snapshots__/macro.test.js.snap
  packages/styled-components/src/macro/test/macro.test.js
  packages/styled-components/src/models/ServerStyleSheet.js
  yarn.lock
Labels: 4.0

#2639 ssr backward-compat fix for ServerStyleSheet
  packages/styled-components/src/models/ServerStyleSheet.js
  packages/styled-components/src/models/test/StyleSheetManager.test.js
Labels: 5.0

#2640 [rfc] use @emotion/stylis
  packages/styled-components/package.json
  packages/styled-components/src/models/StyleSheetManager.js
  packages/styled-components/src/models/test/StyleSheetManager.test.js
  packages/styled-components/src/utils/stylis.js
  yarn.lock
Labels: 5.0

#2634 disable ComponentStyle staticness in non-production modes
  packages/styled-components/src/models/ComponentStyle.js
  packages/styled-components/src/models/test/StyleSheetManager.test.js
  packages/styled-components/src/models/test/__snapshots__/StyleSheetManager.test.js.snap
  packages/styled-components/src/test/__snapshots__/ssr.test.js.snap
  packages/styled-components/src/test/basic.test.js
  packages/styled-components/src/test/constants.test.js
  packages/styled-components/src/test/props.test.js
  packages/styled-components/src/test/rehydration.test.js
  packages/styled-components/src/test/ssr.test.js
  packages/styled-components/src/test/staticCaching.test.js
  packages/styled-components/src/test/styles.test.js
Labels: 5.0

#2622 lower the threshold for the "too many classes" warning
  packages/styled-components/src/test/warnTooManyClasses.test.js
  packages/styled-components/src/utils/createWarnTooManyClasses.js
Labels: 5.0

#2657 add console.error to catch theme references wo prop present
  packages/styled-components/src/models/StyledComponent.js
  packages/styled-components/src/test/theme.test.js
Labels: 4.0
