Repository styled-components/styled-components, pull requests merged in 2019-10, with the labels that each got.

#2798 Fix GroupedTag.insertRules index drifting on failed insertions
  packages/styled-components/src/sheet/GroupedTag.js
  packages/styled-components/src/sheet/test/GroupedTag.test.js
Labels: 5.0, bug :bug:

#2787 Make ThemeProvider error straightforward
  packages/styled-components/src/models/ThemeProvider.js
  packages/styled-components/src/utils/errors.md
Labels: 5.0

#2797 [bugfix] fix imports for react-native-web
  CHANGELOG.md
  packages/styled-components/src/native/index.js
Labels: 4.0

#2820 Memoize theme
  packages/styled-components/src/models/ThemeProvider.js
Labels: 5.0

#2824 shard cGS by runtime instance
  packages/styled-components/src/constructors/createGlobalStyle.js
  packages/styled-components/src/constructors/test/createGlobalStyle.test.js
  packages/styled-components/src/models/GlobalStyle.js
  packages/styled-components/src/test/__snapshots__/ssr.test.js.snap
  packages/styled-components/src/test/rehydration.test.js
Labels: 5.0

#2838 use smaller merging dep
  packages/styled-components/package.json
  packages/styled-components/src/models/StyledComponent.js
  packages/styled-components/src/models/StyledNativeComponent.js
  yarn.lock
Labels: 5.0

#2811 Update css-to-react-native to v3.0.0
  CHANGELOG.md
  packages/styled-components/package.json
  yarn.lock
Labels: 5.0

#2837 disallow /ad/i in generated class names
  CHANGELOG.md
  packages/styled-components/src/utils/generateAlphabeticName.js
  packages/styled-components/src/utils/test/generateAlphabeticName.test.js
Labels: 5.0
